config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'

  resources :items do
    collection do
      get 'search'
    end
    resources :orders, only: [:index, :create]
  end
  resources :users, only: [:show, :edit, :update] do
    resources :addresses, only: [:create, :edit, :update]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[0-9])[a-z0-9]+\z/i,
                                 message: 'は半角英数字を含めて設定してください', allow_blank: true }
  with_options presence: true do
    validates :nickname
    validates :user_birthday
    with_options format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'は全角で入力してください', allow_blank: true } do
      validates :last_name
      validates :first_name
    end
    with_options format: { with: /\A[ァ-ヶ一]+\z/, message: 'は全角カタカナで入力してください', allow_blank: true } do
      validates :last_name_kana
      validates :first_name_kana
    end
  end

  has_many :items
  has_one :address
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]

  def show
    @user = User.find(current_user.id)
    @items = current_user.items
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to action: :show
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :last_name, :first_name, :last_name_kana, :first_name_kana, :user_birthday)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render "shared/second-header"%>

<%= form_with model: current_user, class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      基本情報の変更
    </h1>
  </div>

  <%= render 'shared/error_messages', model: f.object %>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ニックネーム</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :nickname, class:"input-default", id:"nickname", placeholder:"例) furima太郎", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :last_name, class:"input-name", id:"last-name", placeholder:"例) 山田" %>
      <%= f.text_area :first_name, class:"input-name", id:"first-name", placeholder:"例) 陸太郎" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前カナ(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :last_name_kana, class:"input-name", id:"last-name-kana", placeholder:"例) ヤマダ" %>
      <%= f.text_area :first_name_kana, class:"input-name", id:"first-name-kana", placeholder:"例) リクタロウ" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :user_birthday,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
  </div>
  <div class='register-btn'>
    <%= f.submit "変更する" ,class:"register-red-btn" %>
  </div>
</div>
<% end %>

<%= render "shared/second-footer"%>

app/views/users/show.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# コンテンツ① %>
  <div class='user-contents'>
    <h3 class='title'>会員情報</h3>
    <div class="subtitle" >
    基本情報
    </div>
    <div class='user-info'>
      <div class='nickname-info'>
        <div class="info-text">ニックネーム</div>
        <div><%= @user.nickname %></div>
      </div>
      <div class='email-info'>
        <div class="info-text">メールアドレス</div>
        <%= @user.email %>
      </div>
      <div class='name-info'>
        <div class="info-text">お名前(全角)</div>
        <%= @user.last_name %>  <%= @user.first_name %>
      </div>
      <div class='name-kana-info'>
        <div class="info-text">お名前カナ(全角)</div>
        <%= @user.last_name_kana %>  <%= @user.first_name_kana %>
      </div>
      <div class='birthday-info'>
        <div class="info-text">生年月日</div>
        <%= @user.user_birthday.year %>年 <%= @user.user_birthday.month %>月 <%= @user.user_birthday.day %>日
      </div>
      <div class="info-btn-contents">
        <%= link_to "編集する", edit_user_path(@user), class:"info-edit-btn" %>
      </div>
    </div>
    <div class="subtitle" >
    配送先情報
    </div>
    <div class='user-address-info'>
      <% if @user.address.present? %>
        <div class='nickname-info'>
          <div class="info-text">郵便番号</div>
          <div><%= @user.address.postal_code %></div>
        </div>
        <div class='nickname-info'>
          <div class="info-text">住所</div>
          <div>
          <%= @user.address.prefecture.name %>
          <%= @user.address.city %>
          <%= @user.address.address %>
          <%= @user.address.building %>
          </div>
        </div>
        <div class='nickname-info'>
          <div class="info-text">電話番号</div>
          <div><%= @user.address.phone_number %></div>
        </div>
      <% else %>
        登録されていません
      <% end %>
      <div class="info-btn-contents">
        <%= link_to "編集する", edit_user_address_path(current_user), class:"info-edit-btn" %>
      </div>
    </div>
    <div class="subtitle" >
    カード情報
    </div>
    <div class='user-card-info'>
      登録されていません
    </div>
  </div>
  <%# //コンテンツ① %>

  <%# コンテンツ② %>
  <div class='user-item-contents'>
    <h3 class='title'>出品商品一覧</h3>

    <%# 出品商品一覧 %>
    <ul class='item-lists'>
      <% @items.each do |item| %>
        <li class='list'>
          <%# 商品画像カルーセル %>
          <div class='item-img-content'>
            <ul class='slider'>
              <% item.images.each do |image| %>
                <li>
                  <%= link_to item_path(item.id) do %>
                    <%= image_tag image, class: "item-img" %>
                  <% end %>
                </li>
              <% end %>
            </ul>
            <% if item.order.present? %>
              <div class='sold-out'>
                <span>Sold Out!!</span>
              </div>
            <% end %>
          </div>
          <%# //商品画像カルーセル %>
          <%= link_to item_path(item.id) do %>
            <div class='item-info'>
              <h3 class='item-name'>
                <%= item.name %>
              </h3>
              <div class='item-price'>
                <span><%= item.price %>円<br><%= item.shipping_fee_status.name %></span>
                <div class='star-btn'>
                  <%= image_tag "star.png", class:"star-icon" %>
                  <span class='star-count'>0</span>
                </div>
              </div>
            </div>
          <% end %>

        </li>
      <% end %>
    </ul>
    <%# //出品商品一覧 %>

  </div>
  <%# //コンテンツ② %>

</div>
<%= link_to(new_item_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>出品する</span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>

<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

<%= render "shared/footer" %>