config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'

  resources :items do
    collection do
      get 'search'
    end
    resources :orders, only: [:index, :create]
  end
  resources :users, only: [:show, :edit, :update] do
    resources :addresses, only: [:create, :edit, :update]
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]

  def edit
    @address = current_user.address
  end

  def update
    if current_user.address.update(address_params)
      redirect_to controller: :user, action: :show
    else
      render :edit
    end
  end

  private

  def address_params
    params.require(:address).permit(:postal_code, :prefecture_id, :city, :address, :building, :phone_number).merge(user_id: current_user.id)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/edit.html.erb
<%= render "shared/second-header"%>

<%= form_with model: @address, url: user_address_path(current_user),class: 'transaction-form-wrap',local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      配送先の変更
    </h1>
  </div>

  <%= render 'shared/error_messages', model: f.object %>
      
  <%# 配送先の入力 %>
  <% if current_user.address.present? %>
    <%= render "orders/address_form_present", f: f %>
  <% else %>
    <%= render "orders/address_form_blank", f: f %>
  <% end %>
  <%# /配送先の入力 %>

  <div class='buy-btn'>
    <%= f.submit "変更する" ,class:"buy-red-btn", id:"button" %>
  </div>
  
</div>
<% end %>

<%= render "shared/second-footer"%>